app:
  image: ec2-52-19-79-48.eu-west-1.compute.amazonaws.com/jenkins_test:latest
  entrypoint: ["/bin/bash"]
  command: -c "sleep 5 && go-wrapper run"
  environment:
    - "TITLE=Docker Demo"
    - "DB_USER=demo"
    - "DB_PASS=demo"
    - "DB_NAME=demo"
    - "DB_SSL_MODE=disable"
  links:
    - "db:db"
  ports:
    - 8080:8080
  expose:
    - 8080

db:
  image: postgres:latest
  environment:
    - "POSTGRES_USER=demo"
    - "POSTGRES_PASSWORD=demo"
  expose:
    - 5432
